=== mtgkubbur/mtgkubbur.is/data/kubbur-schemas/calendar.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "calendar",
  "type": "array",
  "items": {
    "type": "object",
    "required": ["date", "cube"],
    "properties": {
      "date":      { "type": "string" },
      "cube":      { "type": "string" },
      "cube_slug": { "type": "string" },
      "host":      { "type": ["string", "null"] },
      "players":   { "type": ["number", "null"] },
      "link":      { "type": ["string", "null"] }
    }
  }
}

=== mtgkubbur/mtgkubbur.is/data/kubbur/calendar.json
[
  {
    "date": "2024-04-23",
    "cube": "Meta Memories",
    "cube_slug": "meta-memories",
    "host": "Diddi",
    "players": 13,
    "link": "https://cubecobra.com/cube/list/563f11e1-1852-42db-9651-506ca3c67691"
  },
  {
    "date": "2024-05-07",
    "cube": "Bolti",
    "cube_slug": "bolti",
    "host": "Hjalti",
    "players": 8,
    "link": "https://cubecobra.com/cube/list/bolti-mtgovintage"
  },
  {
    "date": "2024-05-21",
    "cube": "Synergy Cube",
    "cube_slug": "synergy-cube",
    "host": "Tommi",
    "players": 12,
    "link": "https://cubecobra.com/cube/list/SynergyNotSpeed"
  },
  {
    "date": "2024-06-04",
    "cube": "Vintage Hrappur",
    "cube_slug": "vintage-hrappur",
    "host": "Hrappur",
    "players": 8,
    "link": null
  },
  {
    "date": "2024-06-18",
    "cube": "Pauper Cube Diddi",
    "cube_slug": "pauper-cube-diddi",
    "host": "Diddi",
    "players": 7,
    "link": "https://cubecobra.com/cube/list/thepaupercube"
  },
  {
    "date": "2024-07-16",
    "cube": "Synergy Cube",
    "cube_slug": "synergy-cube",
    "host": "Tommi",
    "players": 9,
    "link": "https://cubecobra.com/cube/list/SynergyNotSpeed"
  },
  {
    "date": "2024-07-30",
    "cube": "Meta Memories",
    "cube_slug": "meta-memories",
    "host": "Diddi",
    "players": 10,
    "link": "https://cubecobra.com/cube/list/563f11e1-1852-42db-9651-506ca3c67691"
  },
  {
    "date": "2024-08-13",
    "cube": "Kaldheim Cube",
    "cube_slug": "kaldheim-cube",
    "host": "Oddur",
    "players": 9,
    "link": "https://cubecobra.com/cube/list/344c9708-7bb7-486a-ad50-497634e467b0"
  },
  {
    "date": "2024-08-27",
    "cube": "Bolti",
    "cube_slug": "bolti",
    "host": "Hjalti",
    "players": 7,
    "link": "https://cubecobra.com/cube/list/bolti-mtgovintage"
  },
  {
    "date": "2024-09-10",
    "cube": "Final Destination",
    "cube_slug": "final-destination",
    "host": "Tommi",
    "players": 8,
    "link": "https://cubecobra.com/cube/list/FinalDestination"
  },
  {
    "date": "2024-09-17",
    "cube": "Bolti",
    "cube_slug": "bolti",
    "host": "Hjalti",
    "players": 7,
    "link": "https://cubecobra.com/cube/list/bolti-mtgovintage"
  },
  {
    "date": "2024-10-01",
    "cube": "Nerva's Cube",
    "cube_slug": "nerva-s-cube",
    "host": "Tommi",
    "players": 6,
    "link": "https://cubecobra.com/cube/list/nerva"
  },
  {
    "date": "2024-10-17",
    "cube": "Bolti",
    "cube_slug": "bolti",
    "host": "Hjalti",
    "players": 12,
    "link": "https://cubecobra.com/cube/list/bolti-mtgovintage"
  },
  {
    "date": "2024-11-07",
    "cube": "Horror Cube",
    "cube_slug": "horror-cube",
    "host": "Arnar",
    "players": 9,
    "link": "https://cubecobra.com/cube/list/5eaf4123-9c4d-433d-8e66-474085276f24"
  },
  {
    "date": "2024-11-14",
    "cube": "Bolti",
    "cube_slug": "bolti",
    "host": "Hjalti",
    "players": 8,
    "link": "https://cubecobra.com/cube/list/bolti-mtgovintage"
  },
  {
    "date": "2024-11-21",
    "cube": "Final Destination",
    "cube_slug": "final-destination",
    "host": "Tommi",
    "players": 6,
    "link": "https://cubecobra.com/cube/list/FinalDestination"
  },
  {
    "date": "2024-12-05",
    "cube": "Old Border Cube",
    "cube_slug": "old-border-cube",
    "host": "Diddi",
    "players": 8,
    "link": "https://cubecobra.com/cube/list/3f75c0e8-fb85-408f-bc17-bb2fed74284a"
  },
  {
    "date": "2025-01-09",
    "cube": "Pauper Cube Diddi",
    "cube_slug": "pauper-cube-diddi",
    "host": "Diddi",
    "players": 10,
    "link": "https://cubecobra.com/cube/list/thepaupercube"
  },
  {
    "date": "2025-01-16",
    "cube": "Commander Cube",
    "cube_slug": "commander-cube",
    "host": "Oddur",
    "players": 7,
    "link": "https://cubecobra.com/cube/list/b501ede6-d81f-4beb-84c2-11b5911ace12"
  },
  {
    "date": "2025-01-23",
    "cube": "Binni's Cube",
    "cube_slug": "binni-s-cube",
    "host": "Binni",
    "players": 10,
    "link": null
  },
  {
    "date": "2025-02-06",
    "cube": "Bolti",
    "cube_slug": "bolti",
    "host": "Hjalti",
    "players": 10,
    "link": "https://cubecobra.com/cube/list/bolti-mtgovintage"
  },
  {
    "date": "2025-02-20",
    "cube": "Turbo Cube",
    "cube_slug": "turbo-cube",
    "host": "Bóas",
    "players": 10,
    "link": null
  },
  {
    "date": "2025-03-20",
    "cube": "Vintage Ingvi",
    "cube_slug": "vintage-ingvi",
    "host": "Ingvi",
    "players": 10,
    "link": null
  },
  {
    "date": "2025-04-03",
    "cube": "Meta Memories",
    "cube_slug": "meta-memories",
    "host": "Diddi",
    "players": 6,
    "link": "https://cubecobra.com/cube/list/563f11e1-1852-42db-9651-506ca3c67691"
  },
  {
    "date": "2025-05-08",
    "cube": "Vintage Aron",
    "cube_slug": "vintage-aron",
    "host": "Aron Ívars",
    "players": 10,
    "link": "https://cubecobra.com/cube/list/d2938070-f8e0-4a27-bcdb-b37c0f06632d"
  },
  {
    "date": "2025-06-11",
    "cube": "Final Destination",
    "cube_slug": "final-destination",
    "host": "Tommi",
    "players": 8,
    "link": "https://cubecobra.com/cube/list/FinalDestination"
  },
  {
    "date": "2025-06-26",
    "cube": "Commander Cube",
    "cube_slug": "commander-cube",
    "host": "Oddur",
    "players": 7,
    "link": "https://cubecobra.com/cube/list/b501ede6-d81f-4beb-84c2-11b5911ace12"
  },
  {
    "date": "2025-07-03",
    "cube": "Meta Memories",
    "cube_slug": "meta-memories",
    "host": "Diddi",
    "players": 9,
    "link": "https://cubecobra.com/cube/list/563f11e1-1852-42db-9651-506ca3c67691"
  },
  {
    "date": "2025-07-24",
    "cube": "Pauper Cube Diddi",
    "cube_slug": "pauper-cube-diddi",
    "host": "Diddi",
    "players": 6,
    "link": "https://cubecobra.com/cube/list/thepaupercube"
  },
  {
    "date": "2025-07-31",
    "cube": "Vintage Tommi",
    "cube_slug": "vintage-tommi",
    "host": "Tommi",
    "players": 13,
    "link": null
  },
  {
    "date": "2025-08-14",
    "cube": "Meta Memories",
    "cube_slug": "meta-memories",
    "host": "Diddi",
    "players": 12,
    "link": "https://cubecobra.com/cube/list/563f11e1-1852-42db-9651-506ca3c67691"
  },
  {
    "date": "2025-08-21",
    "cube": "Khans Cube",
    "cube_slug": "khans-cube",
    "host": "Arnar",
    "players": 11,
    "link": "https://cubecobra.com/cube/list/1bd5db34-ec2c-4790-b557-16b3793387eb"
  },
  {
    "date": "2025-08-28",
    "cube": "Stone Soup Cube",
    "cube_slug": "stone-soup-cube",
    "host": null,
    "players": 12,
    "link": null
  },
  {
    "date": "2025-09-04",
    "cube": "Vintage Aron",
    "cube_slug": "vintage-aron",
    "host": "Aron Ívars",
    "players": 7,
    "link": "https://cubecobra.com/cube/list/d2938070-f8e0-4a27-bcdb-b37c0f06632d"
  },
  {
    "date": "2025-09-11",
    "cube": "Final Destination",
    "cube_slug": "final-destination",
    "host": "Tommi",
    "players": 6,
    "link": "https://cubecobra.com/cube/list/FinalDestination"
  },
  {
    "date": "2025-09-11",
    "cube": "Synergy Cube",
    "cube_slug": "synergy-cube",
    "host": "Tommi",
    "players": 6,
    "link": "https://cubecobra.com/cube/list/SynergyNotSpeed"
  },
  {
    "date": "2025-09-18",
    "cube": "Kaldheim Cube",
    "cube_slug": "kaldheim-cube",
    "host": "Oddur",
    "players": 6,
    "link": "https://cubecobra.com/cube/list/344c9708-7bb7-486a-ad50-497634e467b0"
  },
  {
    "date": "2025-09-25",
    "cube": "Bolti",
    "cube_slug": "bolti",
    "host": "Hjalti",
    "players": 8,
    "link": "https://cubecobra.com/cube/list/bolti-mtgovintage"
  },
  {
    "date": "2025-10-02",
    "cube": "Meta Memories",
    "cube_slug": "meta-memories",
    "host": "Diddi",
    "players": 8,
    "link": "https://cubecobra.com/cube/list/563f11e1-1852-42db-9651-506ca3c67691"
  },
  {
    "date": "2025-10-09",
    "cube": "Final Destination",
    "cube_slug": "final-destination",
    "host": "Tommi",
    "players": 9,
    "link": "https://cubecobra.com/cube/list/FinalDestination"
  },
  {
    "date": "2025-10-11",
    "cube": "Meta Memories",
    "cube_slug": "meta-memories",
    "host": "Diddi",
    "players": 8,
    "link": "https://cubecobra.com/cube/list/563f11e1-1852-42db-9651-506ca3c67691"
  },
  {
    "date": "2025-10-11",
    "cube": "Turbo Cube",
    "cube_slug": "turbo-cube",
    "host": "Bóas",
    "players": 6,
    "link": null
  },
  {
    "date": "2025-10-11",
    "cube": "Synergy Cube",
    "cube_slug": "synergy-cube",
    "host": "Tommi",
    "players": 6,
    "link": "https://cubecobra.com/cube/list/SynergyNotSpeed"
  },
  {
    "date": "2025-10-11",
    "cube": "Old Border Cube",
    "cube_slug": "old-border-cube",
    "host": "Diddi",
    "players": 8,
    "link": "https://cubecobra.com/cube/list/3f75c0e8-fb85-408f-bc17-bb2fed74284a"
  },
  {
    "date": "2025-10-11",
    "cube": "Nerva's Cube",
    "cube_slug": "nerva-s-cube",
    "host": "Tommi",
    "players": 6,
    "link": "https://cubecobra.com/cube/list/nerva"
  },
  {
    "date": "2025-10-11",
    "cube": "Pauper Cube Diddi",
    "cube_slug": "pauper-cube-diddi",
    "host": "Diddi",
    "players": 6,
    "link": "https://cubecobra.com/cube/list/thepaupercube"
  },
  {
    "date": "2025-10-11",
    "cube": "Bolti",
    "cube_slug": "bolti",
    "host": "Hjalti",
    "players": 8,
    "link": "https://cubecobra.com/cube/list/bolti-mtgovintage"
  },
  {
    "date": "2025-10-23",
    "cube": "Stone Soup Cube",
    "cube_slug": "stone-soup-cube",
    "host": null,
    "players": 13,
    "link": null
  },
  {
    "date": "2025-10-30",
    "cube": "Stingvi Power Max",
    "cube_slug": "stingvi-power-max",
    "host": "Ingvi",
    "players": 6,
    "link": "https://moxfield.com/decks/PtG-Cyy4MUyyG-rXmjjjQA"
  },
  {
    "date": "2025-11-06",
    "cube": "Bolti",
    "cube_slug": "bolti",
    "host": "Hjalti",
    "players": 8,
    "link": "https://cubecobra.com/cube/list/bolti-mtgovintage"
  },
  {
    "date": "2025-11-13",
    "cube": "Old Border Cube",
    "cube_slug": "old-border-cube",
