=== mtgkubbur/mtgkubbur.is/data/kubbur-schemas/cube_detail.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "cube_detail",
  "type": "object",
  "required": ["cube", "slug", "tier", "summary", "trophy_leaders", "player_rankings", "events"],
  "properties": {
    "cube": { "type": "string" }, "slug": { "type": "string" }, "tier": { "type": "string" },
    "summary": { "type": "object" },
    "trophy_leaders": { "type": "array", "items": {
      "type": "object", "required": ["player","trophies"],
      "properties": { "player": {"type":"string"}, "trophies": {"type":"number"} } } },
    "player_rankings": { "type": "array", "items": {
      "type": "object", "required": ["player","match_w","match_l","match_pct","game_w","game_l","game_pct"],
      "properties": {
        "player": {"type":"string"}, "match_w": {"type":"number"}, "match_l": {"type":"number"},
        "match_pct": {"type":"number"}, "game_w": {"type":"number"}, "game_l": {"type":"number"},
        "game_pct": {"type":"number"} } } },
    "events": { "type": "array", "items": {
      "type": "object", "required": ["date","results"],
      "properties": { "date": {"type":"string"}, "results": {"type":"array"} } } }
  }
}

=== mtgkubbur/mtgkubbur.is/data/kubbur/cubes/flashdance.json
{
  "cube": "Flashdance!",
  "slug": "flashdance",
  "tier": "Medium",
  "summary": {
    "n_events": 2,
    "n_matches": 24,
    "n_players": 12,
    "first_played": "2026-03-19",
    "last_played": "2026-05-28"
  },
  "trophy_leaders": [
    {
      "player": "Aron Elvar",
      "trophies": 1
    },
    {
      "player": "Örvar",
      "trophies": 1
    }
  ],
  "player_rankings": [
    {
      "player": "Aron Elvar",
      "match_w": 3,
      "match_l": 0,
      "match_pct": 100,
      "game_w": 6,
      "game_l": 2,
      "game_pct": 75
    },
    {
      "player": "Binni",
      "match_w": 2,
      "match_l": 1,
      "match_pct": 67,
      "game_w": 5,
      "game_l": 3,
      "game_pct": 62
    },
    {
      "player": "Örvar",
      "match_w": 4,
      "match_l": 2,
      "match_pct": 67,
      "game_w": 9,
      "game_l": 6,
      "game_pct": 60
    },
    {
      "player": "Móses",
      "match_w": 2,
      "match_l": 1,
      "match_pct": 67,
      "game_w": 4,
      "game_l": 3,
      "game_pct": 57
    },
    {
      "player": "Oddur",
      "match_w": 2,
      "match_l": 1,
      "match_pct": 67,
      "game_w": 5,
      "game_l": 4,
      "game_pct": 56
    },
    {
      "player": "Arnar",
      "match_w": 2,
      "match_l": 1,
      "match_pct": 67,
      "game_w": 4,
      "game_l": 4,
      "game_pct": 50
    },
    {
      "player": "Aron Freyr",
      "match_w": 1,
      "match_l": 2,
      "match_pct": 33,
      "game_w": 4,
      "game_l": 4,
      "game_pct": 50
    },
    {
      "player": "Ólafur",
      "match_w": 1,
      "match_l": 2,
      "match_pct": 33,
      "game_w": 3,
      "game_l": 4,
      "game_pct": 43
    },
    {
      "player": "Tommi",
      "match_w": 2,
      "match_l": 4,
      "match_pct": 33,
      "game_w": 6,
      "game_l": 9,
      "game_pct": 40
    },
    {
      "player": "Diddi",
      "match_w": 2,
      "match_l": 4,
      "match_pct": 33,
      "game_w": 6,
      "game_l": 10,
      "game_pct": 38
    },
    {
      "player": "Friðrik",
      "match_w": 1,
      "match_l": 5,
      "match_pct": 17,
      "game_w": 5,
      "game_l": 10,
      "game_pct": 33
    }
  ],
  "events": [
    {
      "date": "2026-05-28",
      "results": [
        {
          "player": "Örvar",
          "match_w": 3,
          "match_l": 0,
          "game_w": 6,
          "game_l": 2,
          "trophy": true
        },
        {
          "player": "Diddi",
          "match_w": 2,
          "match_l": 1,
          "game_w": 5,
          "game_l": 4,
          "trophy": false
        },
        {
          "player": "Ólafur",
          "match_w": 1,
          "match_l": 2,
          "game_w": 3,
          "game_l": 4,
          "trophy": false
        },
        {
          "player": "Tommi",
          "match_w": 1,
          "match_l": 2,
          "game_w": 3,
          "game_l": 4,
          "trophy": false
        },
        {
          "player": "Friðrik",
          "match_w": 0,
          "match_l": 3,
          "game_w": 1,
          "game_l": 6,
          "trophy": false
        }
      ]
    },
    {
      "date": "2026-03-19",
      "results": [
        {
          "player": "Aron Elvar",
          "match_w": 3,
          "match_l": 0,
          "game_w": 6,
          "game_l": 2,
          "trophy": true
        },
        {
          "player": "Binni",
          "match_w": 2,
          "match_l": 1,
          "game_w": 5,
          "game_l": 3,
          "trophy": false
        },
        {
          "player": "Móses",
          "match_w": 2,
          "match_l": 1,
          "game_w": 4,
          "game_l": 3,
          "trophy": false
        },
        {
          "player": "Arnar",
          "match_w": 2,
          "match_l": 1,
          "game_w": 4,
          "game_l": 4,
          "trophy": false
        },
        {
          "player": "Oddur",
          "match_w": 2,
          "match_l": 1,
          "game_w": 5,
          "game_l": 4,
          "trophy": false
        },
        {
          "player": "Tommi",
          "match_w": 1,
          "match_l": 2,
          "game_w": 3,
          "game_l": 5,
          "trophy": false
        },
        {
          "player": "Friðrik",
          "match_w": 1,
          "match_l": 2,
          "game_w": 4,
          "game_l": 4,
          "trophy": false
        },
        {
          "player": "Aron Freyr",
          "match_w": 1,
          "match_l": 2,
          "game_w": 4,
          "game_l": 4,
          "trophy": false
        },
        {
          "player": "Örvar",
          "match_w": 1,
          "match_l": 2,
          "game_w": 3,
          "game_l": 4,
          "trophy": false
        },
        {
          "player": "Diddi",
          "match_w": 0,
          "match_l": 3,
          "game_w": 1,
          "game_l": 6,
          "trophy": false
        }
      ]
    }
  ]
}

=== mtgkubbur/mtgkubbur.is/data/kubbur/cubes/standard-meta-cube.json
{
  "cube": "Standard Meta Cube",
  "slug": "standard-meta-cube",
  "tier": "Other",
  "summary": {
    "n_events": 1,
    "n_matches": 12,
    "n_players": 8,
    "first_played": "2026-07-09",
    "last_played": "2026-07-09"
  },
  "trophy_leaders": [
    {
      "player": "Aron Freyr",
      "trophies": 1
    }
  ],
  "player_rankings": [
    {
      "player": "Aron Freyr",
      "match_w": 3,
      "match_l": 0,
      "match_pct": 100,
      "game_w": 6,
      "game_l": 0,
      "game_pct": 100
    },
    {
      "player": "Einar",
      "match_w": 2,
      "match_l": 1,
      "match_pct": 67,
      "game_w": 4,
      "game_l": 2,
      "game_pct": 67
    },
    {
      "player": "Örvar",
      "match_w": 2,
      "match_l": 1,
      "match_pct": 67,
      "game_w": 4,
      "game_l": 4,
      "game_pct": 50
    },
    {
      "player": "Atli",
      "match_w": 2,
      "match_l": 1,
      "match_pct": 67,
      "game_w": 4,
      "game_l": 4,
      "game_pct": 50
    },
    {
      "player": "Einar Logi",
      "match_w": 1,
      "match_l": 2,
      "match_pct": 33,
      "game_w": 4,
      "game_l": 5,
      "game_pct": 44
    },
    {
      "player": "Tommi",
      "match_w": 1,
      "match_l": 2,
      "match_pct": 33,
      "game_w": 3,
      "game_l": 5,
      "game_pct": 38
    },
    {
      "player": "Diddi",
      "match_w": 1,
      "match_l": 2,
      "match_pct": 33,
      "game_w": 3,
      "game_l": 5,
      "game_pct": 38
    },
    {
      "player": "Anna",
      "match_w": 0,
      "match_l": 3,
      "match_pct": 0,
      "game_w": 3,
      "game_l": 6,
      "game_pct": 33
    }
  ],
  "events": [
    {
      "date": "2026-07-09",
      "results": [
        {
          "player": "Aron Freyr",
          "match_w": 3,
          "match_l": 0,
          "game_w": 6,
          "game_l": 0,
          "trophy": true
        },
        {
          "player": "Örvar",
          "match_w": 2,
          "match_l": 1,
          "game_w": 4,
          "game_l": 4,
          "trophy": false
        },
        {
          "player": "Atli",
          "match_w": 2,
          "match_l": 1,
          "game_w": 4,
          "game_l": 4,
          "trophy": false
        },
        {
          "player": "Einar",
          "match_w": 2,
          "match_l": 1,
          "game_w": 4,
          "game_l": 2,
          "trophy": false
        },
        {
          "player": "Einar Logi",
          "match_w": 1,
          "match_l": 2,
          "game_w": 4,
          "game_l": 5,
          "trophy": false
        },
        {
          "player": "Tommi",
          "match_w": 1,
          "match_l": 2,
          "game_w": 3,
          "game_l": 5,
          "trophy": false
        },
        {
          "player": "Diddi",
          "match_w": 1,
          "match_l": 2,
          "game_w": 3,
          "game_l": 5,
          "trophy": false
        },
        {
          "player": "Anna",
          "match_w": 0,
          "match_l": 3,
          "game_w": 3,
          "game_l": 6,
          "trophy": false
        }
      ]
    }
  ]
}

=== mtgkubbur/mtgkubbur.is/data/kubbur/cubes/inventors-fair.json
{
  "cube": "Inventors' Fair",
  "slug": "inventors-fair",
  "tier": "Medium",
  "summary": {
    "n_events": 2,
    "n_matches": 16,
    "n_players": 11,
    "first_played": "2026-05-21",
    "last_played": "2026-06-18"
  },
  "trophy_leaders": [
    {
      "player": "Aron Freyr",
      "trophies": 2
    }
  ],
  "player_rankings": [
    {
      "player": "Aron Freyr",
      "match_w": 6,
      "match_l": 0,
      "match_pct": 100,
      "game_w": 12,
      "game_l": 5,
      "game_pct": 71
    },
    {
      "player": "Diddi",
      "match_w": 2,
      "match_l": 1,
      "match_pct": 67,
      "game_w": 5,
      "game_l": 2,
      "game_pct": 71
    },
    {
      "player": "Tommi",
      "match_w": 4,
      "match_l": 2,
      "match_pct": 67,
      "game_w": 7,
      "game_l": 5,
      "game_pct": 58
    },
    {
      "player": "Örvar",
      "match_w": 2,
      "match_l": 1,
      "match_pct": 67,
      "game_w": 4,
      "game_l": 3,
      "game_pct": 57
    },
    {
      "player": "Aron Elvar",
      "match_w": 1,
      "match_l": 2,
      "match_pct": 33,
      "game_w": 3,
      "game_l": 4,
      "game_pct": 43
    },
    {
      "player": "Binni",
      "match_w": 1,
      "match_l": 1,
      "match_pct": 50,
      "game_w": 2,
      "game_l": 3,
      "game_pct": 40
    },
    {
      "player": "Aron Ívars",
      "match_w": 0,
      "match_l": 2,
      "match_pct": 0,
      "game_w": 2,
      "game_l": 4,
      "game_pct": 33
    },
    {
      "player": "Daníel",
      "match_w": 0,
      "match_l": 1,
      "match_pct": 0,
      "game_w": 1,
      "game_l": 2,
      "game_pct": 33
    },
    {
      "player": "Atli",
      "match_w": 0,
      "match_l": 3,
      "match_pct": 0,
      "game_w": 2,
      "game_l": 6,
      "game_pct": 25
    },
    {
      "player": "Friðrik",
      "match_w": 0,
      "match_l": 2,
      "match_pct": 0,
      "game_w": 1,
      "game_l": 4,
      "game_pct": 20
    }
  ],
  "events": [
    {
      "date": "2026-06-18",
      "results": [
        {
          "player": "Aron Freyr",
          "match_w": 3,
          "match_l": 0,
          "game_w": 6,
          "game_l": 2,
          "trophy": true
        },
        {
          "player": "Diddi",
          "match_w": 2,
          "match_l": 1,
          "game_w": 5,
          "game_l": 2,
          "trophy": false
        },
        {
          "player": "Tommi",
          "match_w": 2,
          "match_l": 1,
          "game_w": 3,
          "game_l": 3,
          "trophy": false
        },
        {
          "player": "Aron Elvar",
          "match_w": 1,
          "match_l": 2,
          "game_w": 3,
          "game_l": 4,
          "trophy": false
        },
        {
          "player": "Binni",
          "match_w": 1,
          "match_l": 1,
          "game_w": 2,
          "game_l": 3,
          "trophy": false
        },
        {
          "player": "Aron Ívars",
          "match_w": 0,
          "match_l": 2,
          "game_w": 2,
          "game_l": 4,
          "trophy": false
        },
        {
          "player": "Atli",
          "match_w": 0,
          "match_l": 2,
          "game_w": 1,
          "game_l": 4,
          "trophy": false
        }
      ]
    },
    {
      "date": "2026-05-21",
      "results": [
        {
          "player": "Aron Freyr",
          "match_w": 3,
          "match_l": 0,
          "game_w": 6,
          "game_l": 3,
          "trophy": true
        },
        {
          "player": "Örvar",
          "match_w": 2,
          "match_l": 1,
          "game_w": 4,
          "game_l": 3,
          "trophy": false
        },
        {
          "player": "Tommi",
          "match_w": 2,
          "match_l": 1,
          "game_w": 4,
          "game_l": 2,
          "trophy": false
        },
        {
          "player": "Atli",
          "match_w": 0,
          "match_l": 1,
          "game_w": 1,
          "game_l": 2,
          "trophy": false
        },
        {
          "player": "Daníel",
          "match_w": 0,
          "match_l": 1,
          "game_w": 1,
          "game_l": 2,
          "trophy": false
        },
        {
          "player": "Friðrik",
          "match_w": 0,
          "match_l": 2,
          "game_w": 1,
          "game_l": 4,
          "trophy": false
        }
      ]
    }
  ]
}

=== mtgkubbur/mtgkubbur.is/data/kubbur/cubes/stone-soup-cube.json
{
  "cube": "Stone Soup Cube",
  "slug": "stone-soup-cube",
  "tier": "Other",
  "summary": {
    "n_events": 3,
    "n_matches": 49,
    "n_players": 22,
    "first_played": "2025-08-28",
    "last_played": "2025-12-04"
  },
  "trophy_leaders": [
    {
      "player": "Tommi",
      "trophies": 2
    },
    {
      "player": "Binni",
      "trophies": 1
    },
    {
      "player": "Aron Freyr",
      "trophies": 1
    },
    {
      "player": "Diddi",
      "trophies": 1
    }
  ],
  "player_rankings": [
    {
      "player": "Aron Freyr",
      "match_w": 3,
      "match_l": 1,
      "match_pct": 75,
      "game_w": 7,
      "game_l": 2,
      "game_pct": 78
    },
    {
      "player": "Tommi",
      "match_w": 6,
      "match_l": 2,
      "match_pct": 75,
      "game_w": 12,
      "game_l": 5,
      "game_pct": 71
    },
    {
      "player": "Diddi",
      "match_w": 7,
      "match_l": 2,
      "match_pct": 78,
      "game_w": 15,
      "game_l": 7,
      "game_pct": 68
    },
    {
      "player": "Binni",
      "match_w": 4,
      "match_l": 2,
      "match_pct": 67,
      "game_w": 10,
      "game_l": 6,
      "game_pct": 62
    },
    {
      "player": "Arnar",
      "match_w": 2,
      "match_l": 1,
      "match_pct": 67,
      "game_w": 5,
      "game_l": 3,
      "game_pct": 62
    },
    {
      "player": "Aron Elvar",
      "match_w": 3,
      "match_l": 2,
      "match_pct": 60,
      "game_w": 8,
      "game_l": 6,
      "game_pct": 57
    },
    {
      "player": "Örvar",
      "match_w": 4,
      "match_l": 2,
      "match_pct": 67,
      "game_w": 8,
      "game_l": 6,
      "game_pct": 57
    },
    {
      "player": "Einar",
      "match_w": 3,
      "match_l": 3,
      "match_pct": 50,
      "game_w": 8,
      "game_l": 8,
      "game_pct": 50
    },
    {
      "player": "Daníel",
      "match_w": 3,
      "match_l": 3,
      "match_pct": 50,
      "game_w": 8,
      "game_l": 8,
      "game_pct": 50
    },
    {
      "player": "Ingvi",
      "match_w": 2,
      "match_l": 2,
      "match_pct": 50,
      "game_w": 6,
      "game_l": 6,
      "game_pct": 50
    },
    {
      "player": "Siggi",
      "match_w": 2,
      "match_l": 1,
      "match_pct": 67,
      "game_w": 4,
      "game_l": 4,
      "game_pct": 50
    },
    {
      "player": "Atli",
      "match_w": 2,
      "match_l": 1,
      "match_pct": 67,
      "game_w": 3,
      "game_l": 3,
      "game_pct": 50
    },
    {
      "player": "Anna",
      "match_w": 3,
      "match_l": 3,
      "match_pct": 50,
      "game_w": 7,
      "game_l": 8,
      "game_pct": 47
    },
    {
      "player": "Styrmir",
      "match_w": 2,
      "match_l": 4,
      "match_pct": 33,
      "game_w": 6,
      "game_l": 9,
      "game_pct": 40
    },
    {
      "player": "Ólafur",
      "match_w": 1,
      "match_l": 2,
      "match_pct": 33,
      "game_w": 3,
      "game_l": 5,
      "game_pct": 38
    },
    {
      "player": "Aron Gauti",
      "match_w": 0,
      "match_l": 2,
      "match_pct": 0,
      "game_w": 1,
      "game_l": 3,
      "game_pct": 25
    },
    {
      "player": "Hjalti",
      "match_w": 0,
      "match_l": 2,
      "match_pct": 0,
      "game_w": 1,
      "game_l": 4,
      "game_pct": 20
    },
    {
      "player": "Oddur",
      "match_w": 0,
      "match_l": 6,
      "match_pct": 0,
      "game_w": 2,
      "game_l": 12,
      "game_pct": 14
    }
  ],
  "events": [
    {
      "date": "2025-12-04",
      "results": [
        {
          "player": "Diddi",
          "match_w": 3,
          "match_l": 0,
          "game_w": 6,
          "game_l": 1,
          "trophy": true
        },
        {
          "player": "Örvar",
          "match_w": 2,
          "match_l": 1,
          "game_w": 4,
          "game_l": 3,
          "trophy": false
        },
        {
          "player": "Atli",
          "match_w": 2,
          "match_l": 1,
          "game_w": 3,
          "game_l": 3,
          "trophy": false
        },
        {
          "player": "Aron Elvar",
          "match_w": 2,
          "match_l": 1,
          "game_w": 5,
          "game_l": 4,
          "trophy": false
        },
        {
          "player": "Daníel",
          "match_w": 2,
          "match_l": 1,
          "game_w": 4,
          "game_l": 3,
          "trophy": false
        },
        {
          "player": "Binni",
          "match_w": 1,
          "match_l": 2,
          "game_w": 4,
          "game_l": 4,
          "trophy": false
        },
        {
          "player": "Hjalti",
          "match_w": 0,
          "match_l": 2,
          "game_w": 1,
          "game_l": 4,
          "trophy": false
        },
        {
          "player": "Aron Gauti",
          "match_w": 0,
          "match_l": 2,
          "game_w": 1,
          "game_l": 3,
          "trophy": false
        },
        {
          "player": "Tommi",
          "match_w": 0,
          "match_l": 2,
          "game_w": 0,
          "game_l": 3,
          "trophy": false
        }
      ]
    },
    {
      "date": "2025-10-23",
      "results": [
        {
          "player": "Aron Freyr",
          "match_w": 3,
          "match_l": 1,
          "game_w": 7,
          "game_l": 2,
          "trophy": true
        },
        {
          "player": "Tommi",
          "match_w": 3,
          "match_l": 0,
          "game_w": 6,
          "game_l": 0,
          "trophy": true
        },
        {
          "player": "Einar",
          "match_w": 2,
          "match_l": 1,
          "game_w": 4,
          "game_l": 3,
          "trophy": false
        },
        {
          "player": "Ingvi",
          "match_w": 2,
          "match_l": 0,
          "game_w": 4,
          "game_l": 2,
          "trophy": false
        },
        {
          "player": "Örvar",
          "match_w": 2,
          "match_l": 1,
          "game_w": 4,
          "game_l": 3,
          "trophy": false
        },
        {
          "player": "Diddi",
          "match_w": 2,
          "match_l": 1,
          "game_w": 4,
          "game_l": 2,
          "trophy": false
        },
        {
          "player": "Aron Elvar",
          "match_w": 1,
          "match_l": 1,
          "game_w": 3,
          "game_l": 2,
          "trophy": false
        },
        {
          "player": "Ólafur",
          "match_w": 1,
          "match_l": 2,
          "game_w": 3,
          "game_l": 5,
          "trophy": false
        },
        {
          "player": "Anna",
          "match_w": 1,
          "match_l": 2,
          "game_w": 2,
          "game_l": 4,
          "trophy": false
        },
        {
          "player": "Styrmir",
          "match_w": 1,
          "match_l": 2,
          "game_w": 3,
          "game_l": 4,
          "trophy": false
        },
        {
          "player": "Oddur",
          "match_w": 0,
          "match_l": 3,
          "game_w": 0,
          "game_l": 6,
          "trophy": false
        }
      ]
    },
    {
      "date": "2025-08-28",
      "results": [
        {
          "player": "Binni",
          "match_w": 3,
          "match_l": 0,
          "game_w": 6,
          "game_l": 2,
          "trophy": true
        },
        {
          "player": "Tommi",
          "match_w": 3,
          "match_l": 0,
          "game_w": 6,
          "game_l": 2,
          "trophy": true
        },
        {
          "player": "Diddi",
          "match_w": 2,
          "match_l": 1,
          "game_w": 5,
          "game_l": 4,
          "trophy": false
        },
        {
          "player": "Siggi",
          "match_w": 2,
          "match_l": 1,
          "game_w": 4,
          "game_l": 4,
          "trophy": false
        },
        {
          "player": "Anna",
          "match_w": 2,
          "match_l": 1,
          "game_w": 5,
          "game_l": 4,
          "trophy": false
        },
        {
          "player": "Arnar",
          "match_w": 2,
          "match_l": 1,
          "game_w": 5,
          "game_l": 3,
          "trophy": false
        },
        {
          "player": "Styrmir",
          "match_w": 1,
          "match_l": 2,
          "game_w": 3,
          "game_l": 5,
          "trophy": false
        },
        {
          "player": "Einar",
          "match_w": 1,
          "match_l": 2,
          "game_w": 4,
          "game_l": 5,
          "trophy": false
        },
        {
          "player": "Daníel",
          "match_w": 1,
          "match_l": 2,
          "game_w": 4,
          "game_l": 5,
          "trophy": false
        },
        {
          "player": "Oddur",
          "match_w": 0,
          "match_l": 3,
          "game_w": 2,
          "game_l": 6,
          "trophy": false
        },
        {
          "player": "Ingvi",
          "match_w": 0,
          "match_l": 2,
          "game_w": 2,
          "game_l": 4,
          "trophy": false
        }
      ]
    }
  ]
}

=== mtgkubbur/mtgkubbur.is/data/kubbur/cubes/pauper-cube-diddi.json
{
  "cube": "Pauper Cube Diddi",
  "slug": "pauper-cube-diddi",
  "tier": "Low",
  "summary": {
    "n_events": 1,
    "n_matches": 9,
    "n_players": 6,
    "first_played": "2025-10-12",
    "last_played": "2025-10-12"
  },
  "trophy_leaders": [
    {
      "player": "Örvar",
      "trophies": 1
    }
  ],
  "player_rankings": [
    {
      "player": "Victor",
      "match_w": 2,
      "match_l": 1,
      "match_pct": 67,
      "game_w": 5,
      "game_l": 1,
      "game_pct": 83
    },
    {
      "player": "Örvar",
      "match_w": 3,
      "match_l": 0,
      "match_pct": 100,
      "game_w": 5,
      "game_l": 3,
      "game_pct": 62
    },
    {
      "player": "Ólafur",
      "match_w": 1,
      "match_l": 2,
      "match_pct": 33,
      "game_w": 3,
      "game_l": 5,
      "game_pct": 38
    },
    {
      "player": "Aron Gauti",
      "match_w": 0,
      "match_l": 3,
      "match_pct": 0,
      "game_w": 3,
      "game_l": 6,
      "game_pct": 33
    }
  ],
  "events": [
    {
      "date": "2025-10-12",
      "results": [
        {
          "player": "Örvar",
          "match_w": 3,
          "match_l": 0,
          "game_w": 5,
          "game_l": 3,
          "trophy": true
        },
        {
          "player": "Victor",
          "match_w": 2,
          "match_l": 1,
          "game_w": 5,
          "game_l": 1,
          "trophy": false
        },
        {
          "player": "Ólafur",
          "match_w": 1,
          "match_l": 2,
          "game_w": 3,
          "game_l": 5,
          "trophy": false
        },
        {
          "player": "Aron Gauti",
          "match_w": 0,
          "match_l": 3,
          "game_w": 3,
          "game_l": 6,
          "trophy": false
        }
      ]
    }
  ]
}
